apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkaconnectors.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaConnector
    listKind: KafkaConnectorList
    singular: kafkaconnector
    plural: kafkaconnectors
    shortNames:
    - kctr
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            class:
              type: string
            tasksMax:
              type: integer
              minimum: 1
            config:
              type: object
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  lastTransitionTime:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
            observedGeneration:
              type: integer
