apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: kafkaconnectors.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  versions:
  - name: v1alpha1
    served: true
    storage: false
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaConnector
    listKind: KafkaConnectorList
    singular: kafkaconnector
    plural: kafkaconnectors
    shortNames:
    - kctr
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            connectCluster:
              type: object
              properties:
                url:
                  type: string
            class:
              type: string
            tasksMax:
              type: integer
              minimum: 1
            topics:
              type: array
              items:
                type: string
            config:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
